default: &defaults
  adapter: postgresql
  host: localhost

development:
  <<: *defaults
  database: unfuck-dev
  username: postgres
  password: abcdef

test:
  <<: *defaults
  database: unfuck-test

cucumber:
  <<: *defaults
  database: unfuck-test

production:
  <<: *defaults
  database: unfuck-prod
