default: &defaults
  adapter: postgresql
  host: localhost

development:
  <<: *defaults
  database: unfuck-dev

test:
  <<: *defaults
  database: unfuck-test

production:
  <<: *defaults
  database: unfuck-prod
